package jason.app.ibook.commons.api.constant;

public enum CategoryType {
LOCATION,JOB_CATEGORY,FEATURE,SKILL,JOB_TYPE,EDUCATION_LEVEL,WELLFARE,JOB_INDUSTRY,EXPERIENCE, COMPANY_TYPE,SALARY,COMPANY_SIZE;
}
